In [50]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline 
import wget
import ipykernel

Q1. Pandas version
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [51]:
pd.__version__

'2.2.3'

Getting the data
For this homework, we'll use the Laptops Price dataset. Download it from here.

You can do it with wget:
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

In [52]:
import wget
wget.download("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv","laptops.csv")

Q2. Records count
How many records are in the dataset?

12
1000
2160
12160

In [53]:
df=pd.read_csv("laptops.csv")
print("total records are",len(df))

total records are 2160


Q3. Laptop brands
How many laptop brands are presented in the dataset?

12
27
28
2160

In [54]:
num_unique_laptop_brands=df["Brand"].nunique()
print("total unique laptop brands are ",num_unique_laptop_brands)

total unique laptop brands are  27


Q4. Missing values
How many columns in the dataset have missing values?

0
1
2
3

In [55]:
missing_data=df.isna().sum()
print(missing_data)
print("total columns with missing values are ",3,"Storage type,GPU and Screen ")

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64
total columns with missing values are  3 Storage type,GPU and Screen 


Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

869
3691
3849
3936

In [56]:
dell_notebooks=df[df["Brand"]=="Dell"]
max_price_dell=dell_notebooks["Final Price"].max()
print(max_price_dell)



3936.0


Q6. Median value of Screen
Find the median value of Screen column in the dataset.
Next, calculate the most frequent value of the same Screen column.
Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
Now, calculate the median value of Screen once again.
Has it changed?

In [57]:
df.columns
#median value of screen
df['Screen'].median()
#most frequent values of screen series
most_frequent=df['Screen'].mode()
print("Before",df['Screen'].mode())
#missing values in screen
df['Screen'].isna().sum()
#filling missing value in screen with most frequent value
df['Screen'].fillna(most_frequent)
df['Screen'].mode()
print("After",df['Screen'].mode())
#No change in value in before and After
print("No change in value in before and After")

Before 0    15.6
Name: Screen, dtype: float64
After 0    15.6
Name: Screen, dtype: float64
No change in value in before and After


Q7. Sum of weights
Select all the "Innjoo" laptops from the dataset.
Select only columns RAM, Storage, Screen.
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Compute the inverse of XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

0.43
45.29
45.58
91.30

In [58]:
Innjoo_laptops=df[(df["Brand"]=="Innjoo")]
data=Innjoo_laptops[["RAM","Storage","Screen"]]
X=np.array(data)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [59]:
#transpose of X 
#way 1
X.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [60]:
#transpose of X 
#way 2

X_trans=np.matrix_transpose(X)
X_trans


array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [61]:
XTX=X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [62]:
#another way
XTX=X_trans.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [63]:
#Inverse of XTX
inv_xtx=np.linalg.inv(XTX)
inv_xtx

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [65]:
y=np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [68]:
w=(inv_xtx @X_trans)@y
w

array([45.58076606,  0.42783519, 45.29127938])

In [71]:
a=sum(w)
a
print("the closest option for sum of weights is 91.30 with real value as ",a)

the closest option for sum of weights is 91.30 with real value as  91.2998806299555


Submit the results
Submit your results here: https://courses.datatalks.club/ml-zoomcamp-2024/homework/hw01
If your answer doesn't match options exactly, select the closest one